### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#110]
This version seems to be behaving itself.

Thinking to update this (and altair) at CRAN in advance of rstudio::conf - @AliciaSchep any considerations at your end?

**Comment by AliciaSchep** [comment]
Sounds great!  I have a development branch of vlbuildr based off VL4 and I'm hoping to have it merged to master by the time of  rstudio::conf so I think timing this version of vegawidget to be on cran by then would be fantastic.

**Comment by ijlyttle** [comment]
closed in #111
