### ISSUE TITLE
Working example for rendering an Altair Chart (from python) in an RMarkdown file`

### ISSUE THREAD

**Issue by firasm** [vegawidget/vegawidget#112]
Hey all, sorry if this isn't the right place for this (should I post on StackOverflow?), but I'm interested in getting a python Altair (python library, not the R altair library) object to display inside an Rmarkdown document and then knit it to an HTML document. 

I thought [this page](https://vegawidget.github.io/altair/articles/field-guide-rendering.html) must have a working example, but it doesn't yet. I'm happy to help contribute back if I can get my example working.

Here's what happens when I try to render the chart:

<img width="1089" alt="Screen Shot 2020-01-22 at 11 32 00 PM" src="https://user-images.githubusercontent.com/2507459/72964684-6564f200-3d6f-11ea-82ff-7bbdd3a2e325.png">

Here is a minimum bit of code to try and get the chart to show up (will need to unzip it): 

[altair-reticulate.Rmd.zip](https://github.com/vegawidget/vegawidget/files/4101810/altair-reticulate.Rmd.zip)

I have also installed the `png` and `rsvg` packages if that helps. I tried to do `chart1.to_html()` and the `json` output to see if RMarkdown would knit raw html and it wouldn't, at least not inside a code-chunk.

Any ideas or suggestions? In theory this should work, just a matter of finagling right? I thought vegawidget might help here.

Here's the chart I'm hoping will show up from the above code:
![visualization-14](https://user-images.githubusercontent.com/2507459/72965044-369b4b80-3d70-11ea-95d5-5e4111e5792c.png)

**Comment by ijlyttle** [comment]
Here's a way that I found - I hope it preserves the spirit of what you want to do: https://gist.github.com/ijlyttle/aa314d02b5f7f85702ea2a648393b21f

**Comment by firasm** [comment]
Amazing!! Thanks @ijlyttle, that's precisely what I was after, The key was to run the display command as an R code chunk rather than python.

Let me know if you'd like me to send a PR for this [here](https://vegawidget.github.io/altair/articles/field-guide-rendering.html) as it's pretty bare-bones at the moment, but otherwise, this is now resolved so closing issue.
