### ISSUE TITLE
consider deleting the comparison with ggplot2 and ggvis in the docs

### ISSUE THREAD

**Issue by g3o2** [vegawidget/vegawidget#114]
> To be clear, although Vega-Lite offers a grammar-of-graphics, this package does not offer a user-friendly framework to compose graphics, like those provided by ggplot2 or ggvis.

ggplot2 or ggvis being supposedly more user-friendly than vegawidget is IMO an inaccurate and unclear statement. Let the users be the judge of that. You’ve done amazing work here!

**Comment by ijlyttle** [comment]
Thanks for the kind words - my intention was to say that *this* package is designed to render visualizations, not compose them (as ggplot2 and ggvis do). This package is designed to be relied upon by other packages that compose, like [vlbuildr](https://vegawidget.github.io/vlbuildr/).

I'll leave this open as a reminder to refresh the docs!

**Comment by g3o2** [comment]
Hmm, however, as a matter of fact _this_ package is designed to compose visualizations as well. The only differentiating factor is that the composing is done in a declarative manner and not through functions.

**Comment by ijlyttle** [comment]
Addressed in #153, thanks!
