### ISSUE TITLE
export.png and export.svg can apparently not be provided separately in `vega_embed()`

### ISSUE THREAD

**Issue by g3o2** [vegawidget/vegawidget#115]
According to [vega-embed](https://github.com/vega/vega-embed), the `export` property is not a boolean but an object of booleans, i.e. `export : {svg: true, png: true}`. In vegawidget, all one can do as of now is to set `export` to either TRUE or FALSE in R, which is not in line with vega-embed features. 

Consequently, how to provide the two subproperties separately via `vega_embed()` ? 

Based on this documentation, I've tried in R to specify `export: list(png = TRUE, svg = FALSE)`, which does not pass the requirement that `export` should coerce to logicial. Furthermore, I've noticed that the `actions` argument is tested for valid names, which exclude `png` and `svg`.

**Comment by ijlyttle** [comment]
It looks like I need to adjust the logic in the `vega_embed()` function - thanks for pointing this out!
