### ISSUE TITLE
is the rlang package dependency really necessary?

### ISSUE THREAD

**Issue by g3o2** [vegawidget/vegawidget#116]
Please consider this issue a suggestion only.

I've noticed that in some functions (e.g. `vega_embed()`), rlang is used instead of R base functions. For example, some assertions test whether a list is named or not using `rlang::is_named(mylist)`.
In R base, this could be written as `!is.null(names(mylist))`.

Given that rlang is still not 1.0.0, is it worth risking the package code to break in future in case that the rlang API breaks ? Maybe this will become more relevant, once you plan vegawidget's own production release.

P.S.: as a side note, `assertthat` is itself only 0.2 for a weird reason, even though for years this package has been quite conservative as regards interface changes, probably because it builds on very simple R base components, which won't evolve that much either. This is unlike the `dplyr` package, which broke the API at several releases and as of today is also still only 0.8.

**Comment by ijlyttle** [comment]
The rlang stuff comes in very handy for the tidy eval for shiny.

That said, I should probably make an inventory of the rlang functions being and see how stable each is claimed to be.
