### ISSUE TITLE
`as_vegaspec.json()` breaks UTF-8 encoding

### ISSUE THREAD

**Issue by g3o2** [vegawidget/vegawidget#117]
Any non-ASCII characters will look weird if the json file is encoded under UTF-8. The issue does not appear to stem from the `jsonlite::fromJson()` function call, for the latter correctly imports the json file. Due to web browser technology, vega-lite specifications provided as json files may often be encoded with UTF-8.

Current workarounds are:

* manually import the spec from json: `jsonlite::fromJSON(json_file, simplifyVector = FALSE, simplifyDataFrame = FALSE)` - no more need to use `as_vegaspec()` in that case;
* or change the encoding of the json file from UTF-8 to ANSI and use `as_vegaspec()` as advertised.

**Comment by g3o2** [comment]
Here is some code to test for the above alleged behaviour, which I can unfortunately not manage to retrace:

```R
fileConn <- file("test_encoding_utf8.vl4.json", encoding = "UTF-8")
writeLines(
  c("{",
    "  \"$schema\": \"https://vega.github.io/schema/vega-lite/v4.json\",",
    "  \"description\": \"ceci une version allégée d'une spécification vega-lite\"",
    "}"
  ),
  fileConn
  )
close(fileConn)

myspec_good <- jsonlite::fromJSON("test_encoding_utf8.vl4.json", simplifyVector = FALSE, simplifyDataFrame = FALSE)
myspec_good$description

myspec_bad <- vegawidget::as_vegaspec("test_encoding_utf8.vl4.json")
myspec_bad$description

myspec_good$description == myspec_bad$description
```

On my computer, the following output is generated:

```R
> myspec_good$description
[1] "ceci une version allégée d'une spécification vega-lite"

> myspec_bad$description
[1] "ceci une version allÃ©gÃ©e d'une spÃ©cification vega-lite"

> myspec_good$description == myspec_bad$description
[1] FALSE
```

From this, I can only conclude that something is applied to the specification within the `as_vegaspec()` function chain, which somehow appears to (unsuccessfully) convert the UTF-8 encoded characters into another encoding.

**Comment by ijlyttle** [comment]
This took me way longer than it should - got it fixed by considering the `encoding` in `as_vegaspec()`. Also added a test, following your very clear example.

Thanks! (getting closer to CRAN, too)
