### ISSUE TITLE
should vega_embed()'s `$actions$editor` be set to `FALSE` by default ?

### ISSUE THREAD

**Issue by g3o2** [vegawidget/vegawidget#119]
Given the fact that the most typical use case of vegawidget will be to paste the data within the spec via the `values` property, I wonder whether or not it would be safer from a data protection point of view to set the "Open in Vega Editor" action to `FALSE` by default.

In the javascript version of vega-embed, the default is set to `true` and the risk of confidential data leaking to the vega editor may be as real, though the most common use case there would be to reference the data by `url` rather than `values`. R users may not be necessarily aware that they are sending their data over the web by clicking on that link with their data embedded within the vega(-lite) spec.

**Comment by ijlyttle** [comment]
A while ago, I asked this [question on slack](https://vega-js.slack.com/archives/C3N418BQD/p1572617371002700), the gist of the answer is that all the data stays on your browser unless:

- you make a PDF
- you save your work using a URL

Perhaps a can put a note to this effect in the `vega_embed()` docs.
