### ISSUE TITLE
Cannot print vegawidget in rmarkdown

### ISSUE THREAD

**Issue by rikardn** [vegawidget/vegawidget#126]
I am trying to output multiple vega-lite plots using print in the same chunk in rmarkdown without success. The only way I can output is to let the final result of a chunk be the widget.

This markdown doesn't work:
````
---
title: "vegatest"
output: html_document
---

```{r test, echo=FALSE}
library(vegawidget)
print(spec_mtcars)
```
````

But this works:

````
---
title: "vegatest"
output: html_document
---

```{r test, echo=FALSE}
library(vegawidget)
spec_mtcars
```
````

**Comment by ijlyttle** [comment]
Thanks - got this sorted out in #134 - should be good-to-go in the dev version.
