### ISSUE TITLE
will there be a new cran build ?

### ISSUE THREAD

**Issue by g3o2** [vegawidget/vegawidget#127]
It would be useful to have at least the latest patches on board for vegawidget, in particular #122. Updating the underlying js packages would also be nice, even though this can already be done manually by any R user.
This will allow vegawidget to remain on par with the current releases of vega-embed, vega-lite and vega.

**Comment by ijlyttle** [comment]
You're right - I had the thought of keeping current with Altair but then wanted to wait until Altair caught up with the arc-marks in Vega-Lite. 

Let me find some time to get this done soon.

**Comment by ijlyttle** [comment]
latest Vega-Lite release is now supported on `master` - working towards CRAN release.

closing in favor of #151

**Comment by ijlyttle** [comment]
just to note vegawidget 0.3.2 is now on CRAN
