### ISSUE TITLE
`timeUnit` not working

### ISSUE THREAD

**Issue by earowang** [vegawidget/vegawidget#128]
When specifying `timeUnit` in the spec, the chart cannot be rendered. But the corresponding JSON spec works fine in the vega editor. The `timeUnit` section in the vignette also seems to show the issue https://vegawidget.github.io/vegawidget/articles/articles/dates-times.html#vega-lite-time-unit

```r
data <- jsonlite::fromJSON('[
      {"date": "Sun, 01 Jan 2012 00:00:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:01:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:02:00", "distance": 2},
      {"date": "Sun, 01 Jan 2012 00:03:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:04:00", "distance": 4},
      {"date": "Sun, 01 Jan 2012 00:05:00", "distance": 2},
      {"date": "Sun, 01 Jan 2012 00:06:00", "distance": 5},
      {"date": "Sun, 01 Jan 2012 00:07:00", "distance": 2},
      {"date": "Sun, 01 Jan 2012 00:08:00", "distance": 6},
      {"date": "Sun, 01 Jan 2012 00:09:00", "distance": 4},
      {"date": "Sun, 01 Jan 2012 00:10:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:11:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:12:00", "distance": 3},
      {"date": "Sun, 01 Jan 2012 00:13:00", "distance": 0},
      {"date": "Sun, 01 Jan 2012 00:14:00", "distance": 2},
      {"date": "Sun, 01 Jan 2012 00:15:00", "distance": 3}
    ]')

library(vegawidget)
list(
  `$schema` = vega_schema(), # specifies Vega-Lite
  data = list(values = data),
  mark = "bar",
  encoding = list(
    x = list(field = "date", timeUnit = list(unit = "minutes"), type = "temporal"),
    y = list(field = "distance", aggregate = "sum", type = "quantitative")
  )
) %>%
  as_vegaspec()
```

**Comment by g3o2** [comment]
@earowang AFAIR `timeUnit` appears to be a recent property in vega-lite ("recent" as in this year) - correct me if I'm wrong. The `vega-lite.min.js` build in vegawidget dates back to something like late 2019 / early 2020 and has unfortunately aged quickly this year due to several updates on both vega-lite and vega.

Until vegawidget is updated, you can update the vega, vega-lite and vega-embed files yourself in the `vegawidget\htmlwidgets` subfolder, that is if you wish it so.

**Comment by ijlyttle** [comment]
Hi @earowang, 

@g3o2 is right, this is a matter of Vega-Lite getting ahead of vegawidget. Until the PR is merged, you can use:

```r
devtools::install_github("vegawidget/vegawidget@vl-4.14.0")
```

Using this newer version, it works for me...

Hoping to get things in order to submit to CRAN again soon.

All being well, I'll close this issue when #133 is merged.

**Comment by earowang** [comment]
Thanks Ian. Yes, the new update fixes the issue.
