### ISSUE TITLE
Rendering vegalite plots in Jupyter lab 

### ISSUE THREAD

**Issue by saptarshiguha** [vegawidget/vegawidget#129]
Hello
With the appropriate Vega 5 extension, jupyter  Lab renders Vega plots (eg Altair). When using the R kernel would it be possible to render the output of the vegawidget package in a JupyterLab notebook?

Thanks much 
Saptarshi

**Comment by ijlyttle** [comment]
Hi @saptarshiguha,

I don't use jupyter Lab myself, but I wonder if the changes made in https://github.com/vegawidget/altair/pull/136 could be useful.

I hope to have them merged soon, but you can try out the changes by:

```r
devtools::install_github("vegawidget/altair@repr")
```

**Comment by ijlyttle** [comment]
Closing - if this requires further attention, please let me know.
