### ISSUE TITLE
Knitted HTML not including (interactive) figures

### ISSUE THREAD

**Issue by joelostblom** [vegawidget/vegawidget#132]
Thank you for bringing vega-lite/Altair to R and RStudio!

I have noticed that figures and interactive element, such as tooltips, show up fine for me inside an RStudio notebook. However, after knitting, the figures are not present in the output document (I tried HTML, github_document, and PDF). When checking on a friends computer who is running an older version of R (3.6.3), I noticed that for them the figures were included, but as PNGs rather than the HTML vegaspec, so interactivity was lost. Is it possible to get the entire HTML vegaspec to be included when knitting to HTML?

This is the sample code I am running

````
---
title: "Vegawidget html output"
output: html_document
---

```{r}
library("vegawidget")

list(
  `$schema` = vega_schema(), # specifies Vega-Lite
  description = "An mtcars example.",
  data = list(values = mtcars),
  mark = "point",
  encoding = list(
    x = list(field = "wt", type = "quantitative"),
    y = list(field = "mpg", type = "quantitative"),
    color = list(field = "cyl", type = "nominal"),
    tooltip = list(field = "cyl", type = "nominal")
  )
) %>% 
as_vegaspec()
```
````

[Knitted HTML file](https://github.com/vegawidget/vegawidget/files/5640079/Vegawidget.html.output.txt)

This is the output of `devtools::version_info()`:

```
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Antergos Linux              
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  C                           
 ctype    en_US.UTF-8                 
 tz       America/Vancouver           
 date     2020-12-03                  
─ Packages ───────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
 backports     1.1.10  2020-09-15 [1] CRAN (R 4.0.2)
 callr         3.5.0   2020-10-08 [1] CRAN (R 4.0.2)
 cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.2)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.2)
 devtools      2.3.2   2020-09-18 [1] CRAN (R 4.0.3)
 digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.2)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.2)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.2)
 htmlwidgets   1.5.2   2020-10-03 [1] CRAN (R 4.0.2)
 jsonlite      1.7.1   2020-09-07 [1] CRAN (R 4.0.2)
 knitr       * 1.29    2020-06-23 [1] CRAN (R 4.0.2)
 lattice       0.20-41 2020-04-02 [2] CRAN (R 4.0.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.2)
 Matrix        1.2-18  2019-11-27 [2] CRAN (R 4.0.3)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.3)
 pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.2)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.2)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)
 processx      3.4.4   2020-09-03 [1] CRAN (R 4.0.2)
 ps            1.4.0   2020-10-07 [1] CRAN (R 4.0.2)
 R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.2)
 rappdirs      0.3.1   2016-03-28 [1] CRAN (R 4.0.3)
 Rcpp          1.0.5   2020-07-06 [1] CRAN (R 4.0.2)
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.3)
 reticulate  * 1.18    2020-10-25 [1] CRAN (R 4.0.3)
 rlang         0.4.7   2020-07-09 [1] CRAN (R 4.0.2)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.2)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 4.0.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.3)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.2)
 usethis       1.6.3   2020-09-17 [1] CRAN (R 4.0.3)
 vegawidget  * 0.3.1   2020-01-22 [1] CRAN (R 4.0.3)
 withr         2.3.0   2020-09-22 [1] CRAN (R 4.0.2)
 xfun          0.17    2020-09-09 [1] CRAN (R 4.0.2)
 yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.2)
[1] /home/joel/R/x86_64-pc-linux-gnu-library/4.0
[2] /usr/lib/R/library
```

**Comment by cderv** [comment]
Following a comment here https://github.com/rstudio/reticulate/issues/711#issuecomment-738647230, I don't know why but `knitr::knit_print` does not dispatch to `vegawidget:::knit_print.vegaspec()`

In the example above, it works if you add the call directly 
````md
---
title: "Vegawidget html output"
output: html_document
---

```{r}
library("vegawidget")

list(
  `$schema` = vega_schema(), # specifies Vega-Lite
  description = "An mtcars example.",
  data = list(values = mtcars),
  mark = "point",
  encoding = list(
    x = list(field = "wt", type = "quantitative"),
    y = list(field = "mpg", type = "quantitative"),
    color = list(field = "cyl", type = "nominal"),
    tooltip = list(field = "cyl", type = "nominal")
  )
) %>% 
as_vegaspec() %>%
vegawidget:::knit_print.vegaspec()
```
````

<details>
<summary>Result</summary>

![image](https://user-images.githubusercontent.com/6791940/101141791-12a5c900-3615-11eb-8557-56843ee1e1f4.png)

</details>

It seems it worked before https://github.com/vegawidget/vegawidget/issues/112#issuecomment-577780157

**Comment by cderv** [comment]
Also slightly related to https://github.com/vegawidget/vegawidget/issues/126 (Rmarkdown and printing)

**Comment by cderv** [comment]
I believe this is because the `knit_print` method is not registered so not found. If I register, it is working.
Simpler example:

````md
---
title: "vegatest"
output: html_document
---

```{r test, echo=FALSE}
library(vegawidget)
vctrs::s3_register("knitr::knit_print", "vegaspec")
spec_mtcars
```
````

There is something tricky with exporting S3 methods for packages in Suggests. 
From : https://r-pkgs.org/namespace.html#export-s3
> A method for a generic in a suggested package. Namespace directives must refer to available functions, so they can not reference suggested packages. It’s possible to use package hooks and code to add this at run-time, but this is sufficiently complicated that I currently wouldn’t recommend it. Instead, you’ll have to design your package dependencies in a way that avoids this scenario.

I don't know why it works with previous version (just tested with R 3.6.3 on RStudio cloud to confirm), but it is no more the case with R 4.0.0. The methods needs to be registered

* Either dynamically in `.onLoad`
* Either by importing knitr and its generic

This would fix this issue I think

**Comment by joelostblom** [comment]
Great, thank you much for all this info, it is really helpful! Explicitly
registering the S3 method works for me as well.

**Comment by ijlyttle** [comment]
Hi @joelostblom & @cderv,

Sorry for taking so long to get to this - I am just cooking up a PR to take care of this. I'll likely follow the `vctrs::s3_register()` method, as it seems to reach back to R 3.6. In the future, I might use the `@exportS3method` directive once nobody in still using R 3.6...
