### ISSUE TITLE
column name used as field contains `.` fails

### ISSUE THREAD

**Issue by earowang** [vegawidget/vegawidget#145]
If a column name used as field contains `.`, it fails, since `vegalite` interprets `.` as sort of nesting meaning.
```r
library(vegawidget)
list(
  `$schema` = vega_schema(), # specifies Vega-Lite
  data = list(values = iris),
  mark = "point",
  encoding = list(
    x = list(field = "Sepal.Length", type = "quantitative"),
    y = list(field = "Sepal.Width", type = "quantitative")
  )
) %>% 
  as_vegaspec()
```

**Comment by ijlyttle** [comment]
Hi Earo,

You can get around that by using `field = [foo.bar]` or `field = foo.\\bar`, but then you would also need to set the `title`.

This is documented in altair: https://vegawidget.github.io/altair/articles/field-guide-python.html#dots-in-variable-names, but it should be documented in vegawidget, as well. (Also, I need to find a different dataset that has dots in the names...)
