### ISSUE TITLE
rationalize function names and argument-names

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#15]
it would be good to have standard definitions (and names) of function arguments

this will involve judicious use of the `@inheritParams` tag

**Comment by ijlyttle** [comment]
Given @AliciaSchep's [suggestion](https://github.com/vegawidget/vegawidget/issues/20#issuecomment-407261086), this seems the place to propose a new function-naming scheme:

### Gateway functions

I think these functions should be exempted from the `vw_` scheme because they have roots in other places and serve as the gateway to the package (I need to find a better way to express this idea):
 
`as_vegaspec()`
`vegawidget()`
`vegawidgetOutput()`
`renderVegawidget()`
`use_vegawidget()` - not done yet, but a usethis-style templating function to let other packages (e.g. altair) import and export these functions easily.

### Other functions

In thinking to spend a little time staring at this list, as I am torn on on functions like `vega_embed()`.

`vw_as_json()`
`vw_autosize()`
`vw_create_block()`, `vw_create_block_gistid()`
`vw_retrieve_block()`
`vw_block_config()`
`vw_examine()`
`vw_spec_mtcars`
`vw_spec_version()`
`vw_to_png()`
`vw_to_svg()`
`vw_vega_embed()`
`vw_vega_version()`
`vw_write_png()`
`vw_write_svg()`

**Comment by AliciaSchep** [comment]
I think for `vega_embed`  it makes sense to omit the `vw_`, partially because it has `vega` in the name (like all the other exempted functions in list above).  I would lean towards including `vw` for `block_config` so that the name is tied to this package specifically (even if no package currently has a similar function, other widget packages might in future?).  Then it also helps keep the rule of thumb that the function in package either has 'vega' in name or is prefixed by 'vw_'....

**Comment by ijlyttle** [comment]
Thanks! 

Sorry for not noticing this earlier, I must have been too "busy" wrapping my head around the ideas and tweaking them. I think we are essential agreement (thanks for your patience); I just need to settle `block_config()` and `png_bin()` in my head.

Let me adjust the proposal above to what you suggest, and I will stare some more...

On the one hand, I'm likely thinking about this too much - on the other hand, this is best change to make the changes.

**Comment by ijlyttle** [comment]
@AliciaSchep, having had a chance to stare at it for a bit, I like this!

I had a scheme where `vs_` would imply that the function took a vegaspec, but I think it ran the risk of being too-fragile. Your proposal of using `vw_` and linking it to the package name seems much more robust. Thanks again!

These remaining points might be fine as they are, but they both seem a little unsettled in my eyes.

- name for example specs, e.g. `vw_ex_mtcars` (`vw_mtcars`?)
- name for `vw_png_bin()`, which takes the dataURI string from `vw_to_png()` and turns it into a raw vector. 

We need `vw_png_bin()` internally - if it's not exported, then we don't care. But it seems useful enough to export in case someone wants the binary rather than the dataURI string.
 
Thanks again - of course, any input you have on anything is most welcome!

**Comment by ijlyttle** [comment]
Just to note that, non-withstanding new proposals on example-spec naming or `vw_png_bin()`, I will begin implementing [this](https://github.com/vegawidget/vegawidget/issues/15#issuecomment-407394555).

@AliciaSchep, thanks!

**Comment by ijlyttle** [comment]
I think I have things switched over now - I'll leave this open for a while in case we need to adjust anything.

**Comment by AliciaSchep** [comment]
Looks good!  Re the example spec, I think having `spec` in the name is nice.  `vw_mtcars_spec`, `mtcars_spec`, `spec_mtcars`, `vw_spec_mtcars`, etc.  I think other packages that use the prefix convention sometimes exempt data sets from that convention.

**Comment by ijlyttle** [comment]
Ha! This is perfect! I mean this absolutely earnestly that I had a good laugh when, upon taking your response into consideration, I realized `spec_mtcars` revealed itself to still be "it".

I like its conciseness, that `spec_` denotes that it is data, and seems namespace-safe. 

I'll change it back...

**Comment by ijlyttle** [comment]
Reverted in 71b64c1

Closing this, as I think everything is ironed out and implemented 🎉
