### ISSUE TITLE
Vega-Lite 5

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#159]
Hello @AliciaSchep @sa-lee @earowang!

You have doubtless seen the news: https://github.com/vega/vega-lite/releases/tag/v5.0.0, with support for signals!

At some point in the next few days, I intend to build a `vegalite-5` branch, then seek your approval to merge it into `master` (should change that to `main`), then to CRAN.

**Comment by ijlyttle** [comment]
This gives a handy view of [what has changed in vega-embed](https://github.com/vega/vega-embed/compare/v6.12.2...v6.15.2?diff=split#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) from the version used by CRAN vegawidget (6.12.2) to the version available as of this comment (6.15.2).

It looks like they have provided a `bind` option, which we could use to specify which input elements we want to bind to which signals (parameters). As always, I'll have to read more.

**Comment by AliciaSchep** [comment]
@ijlyttle did you end up trying out the new version?  I've finally gotten around to taking a look at the new functionality and am interested in exploring the new params functionality! I made an attempt to update the dependencies file for this package, and things mostly seemed to work with the exception of the `vw_to_vega` function.  Wondering if it makes sense to try to use the vega-lite command line utilities more directly in this package? I guess it requires either including a bunch of node modules or having the user install them themselves? Maybe have it [run via `npx`](https://vega.github.io/vega-lite/usage/compile.html#using-npx)?

**Comment by ijlyttle** [comment]
Sorry for late reply - life got in the way for a while - in my branch I was having similar sorts of troubles - I'll pick this up again this weekend!
