### ISSUE TITLE
NA field is dropped when spec is converted to JSON

### ISSUE THREAD

**Issue by sharlagelfand** [vegawidget/vegawidget#160]
Hi all! Thank you for a great package - so wonderful and easy to use :)

I'm not sure whether I have a bug, or a question needing advice... I have a situation where a variable being plotted contains an `NA` value. It appears fine in an actual plot:

``` r
library(vegawidget)
library(dplyr)

penguins_count <- penguins %>%
  count(sex)

penguins_count
#> # A tibble: 3 x 2
#>   sex        n
#>   <fct>  <int>
#> 1 female   165
#> 2 male     168
#> 3 <NA>      11

sex_bar <- list(
  `$schema` = vega_schema(),
  data = list(values = penguins_count),
  mark = "bar",
  encoding = list(x = list(field = "sex", type = "nominal"),
                  y = list(field = "n", type = "quantitative"))
) %>%
  as_vegaspec()

sex_bar
```

![visualization (3)](https://user-images.githubusercontent.com/15895337/116716962-5b846280-a9a6-11eb-8923-eca21de9f98a.png)

But when the spec is converted to JSON, the `sex` field doesn't appear in the third data values:

```r
sex_bar %>%
  vw_as_json()
```

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {
        "sex": "female",
        "n": 165
      },
      {
        "sex": "male",
        "n": 168
      },
      {
        "n": 11
      }
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "sex",
      "type": "nominal"
    },
    "y": {
      "field": "n",
      "type": "quantitative"
    }
  }
} 
```

So I'm guessing this is some issue with `NA` versus `NULL`! I know you have a note about this [here](https://vegawidget.github.io/vegawidget/articles/articles/vegaspec.html#gotchas)

> If the JSON needs a null, supply a NULL from R.

But as I'm sure you all know, getting something to be `NULL` in a dplyr chain or in a tibble is... tricky!

Maybe there's some way I'm missing to coerce this to `NULL` first myself, or if it may be a bug (opportunity for enhancement 😁 ) on the `vegawidget` site to convert from `NA` in R to `null` in JS?

Thanks so much!!

**Comment by sharlagelfand** [comment]
You know, I don't think this is really a vegawidget or vega lite problem, since that spec [renders just fine](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoCHAAeaEADNEOuIpDzUARgBsYgL4KT5y8kH2Sk5uABxeoMHOHgC6XiDIAE4A1pZMSAkOcLJQbMo0smRooBaa1jRwgsqWphZKmACeOPbosmwI+TogcfVFZRVVLQ4NTZYAjgxIsph0ajSkXR4eQA) - I think this is a "me" problem for trying to partake in some off label usage of vegawidget 😂 I'll close this!

**Comment by ijlyttle** [comment]
Hi @sharlagelfand, 

I think this is worth chasing down, particularly as the "leave it out" version fails in Vega-Lite, [it has to be defined as a `null`](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoCHAAeaEADNEOuIpDzUARgBsYgL4KT5y8kH2Sk5uABxePhaosgyCgkFozs4eALpeIMgATgDWlkxIGQ5wslBsyjSyZGigkaBWNHCCypamFkqYAJ449uiybAjlOiBp7VXW9Y2W8m2d3SAAjgxIsph0ajSkQx4eQA).

I'll keep noodling on this, thanks for the heads-up!

**Comment by ijlyttle** [comment]
Hi again @sharlagelfand,

It turns out that `jsonlite::toJSON()` needed a little more persuasion. 

FWIW, I think the next CRAN release will be once we get Vega-Lite 5 sorted out, so you may wish to use the dev version for now.

**Comment by sharlagelfand** [comment]
Oops big delay @ijlyttle! Thanks for the update on this :) I'll keep an eye on the versions (I think it's actually okay for my needs right now), but definitely excited for V5!! Thanks again 😻
