### ISSUE TITLE
to_png(), write_png(), also for svg

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#18]
maybe this can (eventually) help with the appearance of knitted static documents

**Comment by ijlyttle** [comment]
I was thinking about a public function: `to_image()` with an argument for `type` - but this would not be type-stable.

We could have an internal function `.to_image()`, to help with duplication.

We could have function `write_image()` with a `type` argument. This would be ok because we are using a `type` to determine a side-effect - our function would return the spec. We could offer `write_png()` and `write_svg()` as syntactic sugar.

## To image

```r
# internal function
.to_image <- function(spec, type = c("png", "svg")) {

  # convert to vega

  # call V8 to return image

  img
}
```

```r
to_png <- function(spec) {
  .to_image(spec, type = "png")
}

to_svg <- function(spec) {
  .to_image(spec, type = "svg")
}
```

## Save image

```r
write_image(spec, path, type = NULL) {

  # try to determine `type` from path

  if (identical(type, "png")) {
    spec <- write_png(spec, path)
  }

  if (identical(type, "svg")) {
    spec <- write_svg(spec, path)
  }

  spec
}
```

```r
write_png(spec, path) {

  spec
}

write_svg(spec, path) {

  spec
}
```

**Comment by ijlyttle** [comment]
This has been an exercise in frustration (so good learning, if Hadley is to be believed).

In the long run, I would like for these function to provide publication-quality graphics.

In the short run, I am coming up against my limitations.

The original idea was to use **V8** to drive some code that uses the [vega-view](https://github.com/vega/vega-view#image-export) API for image-generation.

The problem is that these functions rely on JS supplied by the browser - not just the JS supplied by vega. Thus we are stuck trying to do things using V8.

The standard way to grab an image of an htmlwidget is to use phantomJS via **webshot**; this is [implemented](https://github.com/hrbrmstr/vegalite/blob/cdf7ee9c90bb71661ba00e20e7f6575acbf2e1c8/R/phantom.r) in **vegalite**. This is seems the best way-to-go for the moment - but we will be limited to PNG.

We *should* be able to get SVG - but I can't get it to work - the limitation right now might be that vega.js (fortified by promise and symbol polyfills) does not have access to `setTimeout()`. Someone has come across this [issue](https://github.com/jeroen/V8/issues/18) already in V8.  I tried the workaround - to supply an empty function, but I could not get a sensible response from my V8 session.

This could be because the empty function messed things up. This could be because I don't know what I'm doing. To try to figure this out, I could try to generate an SVG within a browser console.

**Comment by ijlyttle** [comment]
Refining ideas on what to do "for now"
- implement `write_png()` and `to_png()` along the lines of the vegalite implementation 
- "outsource" the headless way of doing things to altair: https://altair-viz.github.io/user_guide/saving_charts.html
- leave a note in this documentation about the altair implementation (being careful not to invoke a Suggests, as that would cause a circular reference)

**Comment by AliciaSchep** [comment]
Hi @ijlyttle,

I think I have found a way to do the 'svg' part using [webdriver](https://github.com/rstudio/webdriver).  Involves saving an html version of widget, then running a script using the webdriver to get the svg.  Also requires exposing the 'view' in the widget (something I was already exploring with shiny experimentation).  I think this approach has less dependencies than the altair approach (which requires selenium, and might be replicable in R using RSelenium).

Here is a sample code snippet that returned a svg:

```r
pjs <- webdriver::run_phantomjs()
ses <- Session$new(port = pjs$port)
ses$go("example_widget.html")
ses$setTimeout(500)
svg <- ses$executeScriptAsync("var done = arguments[0];
                                getVegaView('htmlwidget-a36d9bcb3cbd26ec2942').toSVG().then(function(svg){done(svg)}).catch(function(err) {console.error(err)});")
```

Note that it calls a javascript function called `getVegaView` which is something I put together for shiny interaction purposes... I can put together a PR wrapping this R snippet into a function which takes in widget plus the JS changes for exposing the view

As a footnote, another approach is to have people install node + vega and call vg2svg or vg2png -- what [ggvis does](https://github.com/rstudio/ggvis/blob/d9cbbf5de5a6a4166672e48a69d0cc9900ab2bf2/R/export.R), but has [led to problems](https://github.com/rstudio/ggvis/issues/382)

**Comment by AliciaSchep** [comment]
One note @ijlyttle:  I think for the call to webdriver, there should likely be some kind of closing / clean up action for the process & session started.  I have added a question to the webdriver repo to hopefully get some guidance on this: https://github.com/rstudio/webdriver/issues/53

**Comment by ijlyttle** [comment]
Thanks, sounds quite sensible! 

I was just about to close the issue, but it's worth keeping open for this.

**Comment by ijlyttle** [comment]
Given the current move towards node.js, this will likely end up differently than we thought in July.

**Comment by ijlyttle** [comment]
closing this, as we have moved away from webdriver
