### ISSUE TITLE
Error with Shiny 1.7.1

### ISSUE THREAD

**Issue by rhenkin** [vegawidget/vegawidget#182]
Hi, the CRAN release and latest dev version are not working with the latest Shiny version.
I did manage to make it work with Shiny 1.6.0 on R 4.0.5 (MacOS Big Sur 10.16)
Session info that works:

> R version 4.0.5 (2021-03-31)
> 
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Big Sur 10.16
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] tibble_3.1.6     vegawidget_0.3.3 shiny_1.6.0     
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.7        rstudioapi_0.13   magrittr_2.0.1    xtable_1.8-4      R6_2.5.1          rlang_0.4.12     
>  [7] fastmap_1.1.0     fansi_0.5.0       tools_4.0.5       utf8_1.2.2        cli_3.1.0         jquerylib_0.1.4  
> [13] withr_2.4.3       htmltools_0.5.2   ellipsis_0.3.2    yaml_2.2.1        digest_0.6.29     assertthat_0.2.1 
> [19] lifecycle_1.0.1   crayon_1.4.2      later_1.3.0       vctrs_0.3.8       sass_0.4.0        htmlwidgets_1.5.4
> [25] promises_1.2.0.1  fs_1.5.2          glue_1.6.0        cachem_1.0.6      mime_0.12         pillar_1.6.4     
> [31] compiler_4.0.5    bslib_0.3.1       jsonlite_1.7.2    httpuv_1.6.4      pkgconfig_2.0.3

If I install the latest Shiny (i.e. install.packages or even the latest dev version), I get the following error when trying to run one of the demos (or my own app). The only difference in the sessionInfo is the Shiny package version.

> Listening on http://127.0.0.1:4663
> Warning: Error in exprToQuo: Don't know how to convert 'vegawidget' to a function; a quosure or quoted expression was expected
>   54: stop
>   53: exprToQuo
>   52: exprToFunction
>   51: shiny::installExprFunction
>   50: htmlwidgets::shinyRenderWidget
>   49: renderVegawidget
>   48: server [/Library/Frameworks/R.framework/Versions/4.0/Resources/library/vegawidget/shiny-demo/data-set-get/server.R#61]
> Error in exprToQuo(expr, env, quoted = TRUE) : 
>   Don't know how to convert 'vegawidget' to a function; a quosure or quoted expression was expected

I guess it's related to this https://github.com/rstudio/shiny/issues/3389 or this https://github.com/rstudio/shiny/pull/3468 ?

**Comment by ijlyttle** [comment]
Yikes! Thanks, I'll have a look...
