### ISSUE TITLE
Do we need to keep copies of the shemae?

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#185]
Hello again @AliciaSchep, @earowang, @sa-lee:

I have been wrestling with some of the infrastructure code, trying to make things more flexible 😅, and found that we have been saving a copy of the schemae for Vega and Vega-Lite, [here](https://github.com/vegawidget/vegawidget/tree/v0.3.3/inst/schema).

None of the {vegawidget} (or {altair}) code uses it - do any of your packages use it?

If not, I'll get rid of it and make things a little simpler and lighter. If so, I'll be happy to provide an access function (perhaps memoised), that would retrieve it from the vega/vega-lite repos.

Thanks!

**Comment by AliciaSchep** [comment]
@ijlyttle -- I am currently including the vega-lite schema in vlbuildr (which I may be [renaming](https://github.com/vegawidget/vlbuildr/pull/74)), which does make use of the schema.  Am currently copying the version from vegawidget directly, but there is no need for it to exist in vegawidget for vlbuildr

**Comment by ijlyttle** [comment]
@AliciaSchep Thanks! 

I'll not get rid of it right away, and I'll be happy to propose a function to retrieve the schema! As this seems to be the season of naming things (I'll think about vlbuildr), I wish that I had named `vega_schema()` something else :)

**Comment by ijlyttle** [comment]
Looking at it a bit more, I think all the pieces are just about there:

 - we'd need a `version` argument to `vega_schema()`, which returns a live URL (which I had forgotten about).
 - we already have a `vw_fetch()` function, which returns the contents of a URL.

I don't know how important memoisation is, but one could:

```r
vega_schema("vega-lite", version = "5.2.0") |> vw_fetch()
```
