### ISSUE TITLE
output id for renderVegawidget so vw_shiny_get_event can reference it

### ISSUE THREAD

**Issue by saptarshiguha** [vegawidget/vegawidget#205]
Hello,
Thanks for a lovely package! Im using the Shiny runtime method and want to avail of `vw_shiny_get_event` which takes the chart id usually provided by `vegawidgetOutput`. However my plotting code in the interactive rmarkdown looks likes

```{r }
```{r}
 renderVegawidget(g))```
```

How do i specify an id for this plot that i can reference in `vw_shiny_get_event` ?

Thanks much!

**Comment by ijlyttle** [comment]
Hi,

`renderVegawidget()` can take a spec or a widget, so you can do something like this:

```r
renderVegawidget(vegawidget(spec, elementId = "foo"))
```

**Comment by saptarshiguha** [comment]
Thank you!

**Comment by saptarshiguha** [comment]
Hello,
I just tried this 
```


```{r }
   renderVegawidget(vegawidget(dd()$scat, elementId = "scat"))
```

```
```{r}
z = vw_shiny_get_event("scat", event = "click", body_value = "datum")
```

But when i run the RMD document in Rstudio, i see this error

```
Warning in renderWidget(instance) :

  Ignoring explicitly provided widget ID "scat"; Shiny doesn't use them
 ```

and inspecting the html, the id is not carried (it should be `<div id='scat'>`
<img width="768" alt="Screen Shot 2022-04-08 at 9 32 25 AM" src="https://user-images.githubusercontent.com/113324/162484142-222f37e1-5a28-48ac-9c81-0e727ae4758f.png">

**Comment by ijlyttle** [comment]
The "shiny" bit didn't totally register with me. Have a look at this example:

https://github.com/vegawidget/vegawidget/blob/main/inst/shiny-demo/event-get/server.R

**Comment by saptarshiguha** [comment]
I see the confusion. I was trying to convert precisly this example you gave to an interactive RMD document.  (i couldn't figure a way to put the ending triple ticks to the chunks below).

```
---
title: "event-get"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(vegawidget)
```

```
```{r}
rct_list_click <-
    vw_shiny_get_event("chart", event = "click", body_value = "datum")
```

```
```{r}
renderVegawidget(vegawidget(spec_mtcars, elementId = "chart"))
```

```
```{r}
 renderPrint({
    (rct_list_click())
  })
```
```
