### ISSUE TITLE
image functions don't work if data is specified by url

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#43]
results in incomplete rendering - see https://gist.github.com/ijlyttle/8cce9bf5458d4e10b4de1e828e4eade1#file-preview-png

check to see if there is a option in webdriver that can help with these cross-site issues.

**Comment by sa-lee** [comment]
I think this has to do with some combination of webdriver and `vega.loader` failing to fetch the URL.

**Comment by ijlyttle** [comment]
I found this: http://phantomjs.org/api/webpage/property/settings.html

and I see that the default for `localToRemoteUrlAccessEnabled` is `false` - I wonder if this is a setting we need to change. I tried to poke around the documentation to https://github.com/rstudio/webdriver, but nothing jumped out at me as to how we might accomplish this.

**Comment by ijlyttle** [comment]
closing this issue, but will likely open another (somewhere) that deals with proxy and node-fetch
