### ISSUE TITLE
JavaScript API

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#53]
Hi @AliciaSchep, @sa-lee, @haleyjeppson:

I have spent some time looking at Alicia's and Stuart's contributions. I want to do justice to the the work you have done; I also want to take an opportunity to see if I could try to "bring everything together", hence this proposal for the JavaScript API.

One of the problems that Haley and I have had using pure JS, as opposed to Shiny, was that the htmlwidget had not instantiated by the time we would try to access the "promise" in the element - so we used `HTMLWidget.addPostRenderHandler` in our JS code. This worked.

When I started to use Alicia's app that tests the bindings, I saw a similar problem. For me, the value of the signal (`"cyl"`) in the spec had to be initialized within the spec to the same value as the shiny  `input$cyl` - independently of each other, which seems sub-optimal.

I fiddled around with `HTMLWidget.addPostRenderHandler`, but that did not seem to work in shiny.

So - I tried something else..., which brings us to the first part of the proposed JS API:

## Vegawidget-object API

The same way that there is an `HTMLWidgets` object in the JS global namesapce, I propose a `Vegawidget` object. At present, there is a single element, a function `find()`, which works like `HTMLWidgets.find()`:

```js
Vegawidget.find(selector)
```

This takes a single argument, a css selector, and returns a *promise* to the vegawidget HTMLObject.

So, instead of writing:

```js
HTMLWidgets.find('#' + id).callView(...);
``` 

We would write:

```js
Vegawidget.find('#' + id).then(function(result) {
  result.callView(...)
});
```

The `Vegawidget.find()` function rejects the promise if the element does not exist, or if it does not have a `"vegawidget"` class; it waits (50 ms at a time) for the HTMLWidgets object to "show up" so that it can resolve the promise.

FWIW, I have got this to work as I expect with Alicia's shiny app. In the ui code, I set value of the slider to `4` - and the rest of the app initializes using that value (instead of the hard-coded `6` in the spec).

## Widget-object API

In addition to the `renderValue` and `resize` (which I need to look at, at some point) functions, I propose these functions:

`getPromise()`

`callView(fn, params, run)`

`insertData(name, data_insert, run)`

`removeData(name, data_remove, run)`

`changeData(name, data_insert, data_remove, run)`

The `getPromise()` function mirrors the "old" `getVegaPromise()` function - it could be useful if you need to "roll your own".

Each of the rest of the functions has a `run` argument that expects a boolean and would default to `true` (is that the right choice?). Some of the vega-view functions are not associated with running anything, so it would be the coders' responsibility to set this to `false` as needed.

The `callView()` function would be implemented largely as Alicia had first proposed, with `fn` being a string naming the function to be called, and `params` being an array of arguments to that function.

The "data" functions are slightly different creatures, which I think merit their own calls. For each, the `name` is a string, as expected. 

However, the `data_*` objects are a little "fuzzy". Let's take `data_insert` - at the R level, we would send a data frame. However, do we serialize the data frame as row-based before sending to to JS (as I think I have seen proposed in the `vw_change_data()` R function) - or do we do it in JS (as I have seen Stuart advocate) by using `HTMLWidgets.dataframeToD3()`, as proposed in the "current" `loadData()` JS function?

I propose to automate this in the new `insertData()` JS function (for example; the idea extends to all the data functions and arguments). I think it could examine its `data_insert` argument - if it is an `object`, but not an `Array`, it could call `HTMLWidgets.dataframeToD3()`. That way, you could send what you want, and `insertData()` (and the other functions) would just "do the right thing".   

In the case of `data_remove`, things can be a bit more complicated as the argument could be a predicate function rather than a dataset. Here, I propose the default value to be `vega.truthy`, following the current behavior. If `data_remove` is a string, we could expect it to be the body of a function we could construct in `JS` using the `Function()` constructor. I would like to be sure that this does not introduce any "Bobby Droptables" risks. That being said, my idea is to specify that the function body assume that the data is represented by the argument `d`, so that a string `
"return(d.count < 5);"` would result in the function:

```{js}
function(d) {return(d.count < 5);}
```

As an aside, I find the terseness of `d` appealing, but I can also see that using `data_remove` as the function-argument might be more consistent and less confusing. Maybe `data`?

I think that wraps up the `*Data()` functions. Alicia had proposed  a couple of other functions that make things easier for the listeners, `addEventListener()` and `addSignalListener()`. Although I think they could be expressed as a `callView`, I don't have any appetite to attack that right away (to be clear, I propose to leave those functions alone right now).

## Shiny-message API

I think that our shiny-message API could mirror the widget-object API, building on Alicia's work using `Shiny.addCustomMessageHandle()`

`"callView"`: `message` would have elements `id`, `fn`, `params`, and `run`.
`"removeData"`: `message` would have elements `id`, `name`, `data_remove`, and `run`.
`"insertData"`: `message` would have elements `id`, `name`, `data_insert`, and `run`.
`"changeData"`: `message` would have elements `id`, `name`, `data_insert`, `data_remove`, and `run`.

## Summary

I know this is *lot* in one post, but I wanted to try to wrap my arms around as much of the JS as I could. I guess the biggest question is "will this be sufficiently expressive" for the rest of what you are proposing?

I hope I have understood and represented faithfully your intentions behind the code you wrote, and I will take responsibility for implementing this in the R code that you-all have written, as well (I may have some questions there).

I have started building this out in my `shiny-interaction-delta` branch, but I will not merge it in to `shiny-interaction` until we are all happy (and it works). 

Looking forward to your thoughts 🙏

**Comment by AliciaSchep** [comment]
On board with the proposed API... not having to set default in both shiny and json to be the same does indeed sound much better! :tada: 

one question though -- why create the Vegawidget object rather than adapting getVegaPromise, e.g.

```js
function getVegaPromise(selector) {

  return new Promise(function(resolve, reject) {
    var htmlWidgetsObj = HTMLWidgets.find(selector);
    if (htmlWidgetsObj !== undefined) {
    		resolve(htmlWidgetsObj);
    } else {
    	setTimeout(function() { getVegaPromise(selector).then(resolve); }, 50);
    }
  });
}
```
(omitting the extra checks from your Vegawidget.find in example above, although I suspect they are important, haven't fully thought through implications yet)

That seems to work in the shiny context as far as I can tell.  Is the motivation behind the object tied to this specific functionality, or a different benefit?

**Comment by ijlyttle** [comment]
Good question 🤔

I think it was a matter of what I got working first - nothing is set in stone, so let me have a think about your suggestion (requires ☕️). 

The extra checks are just to provide an escape hatch if you get the selector wrong, to give a console message and to avoid the thing just waiting for an object that would never show up.

**Comment by ijlyttle** [comment]
Having had a little time to be caffeinated, I think the reason I did it this way was to have access to the `callView()` function, etc., in the object itself. 

This way, I could build the shiny custom-message handlers using syntax like this:

```js
  Shiny.addCustomMessageHandler('callView', function(message) {

    // `message` properties:
    // expected: `id`, `fn`
    // optional: `params`, `run`

    // get, then operate on the Vegawidget object
    Vegawidget.find("#" + message.id).then(function(result) {
      result.callView(message.fn, message.params, message.run);
    });

  });
```

I am still getting my JS "sea-legs" - is there a way to do this using `getVegaPromise()`? 

Or is the suggestion to make such a function available in the `Vegawidget` object?

Or am I completely misunderstanding?

**Comment by AliciaSchep** [comment]
Doing similar thing but with `getVegaPromise`

```js
  Shiny.addCustomMessageHandler('callView', function(message) {

    // `message` properties:
    // expected: `id`, `fn`
    // optional: `params`, `run`

    // get, then operate on the Vegawidget object
    getVegaPromise("#" + message.id).then(function(result) {
      result.callView(message.fn, message.params);
    });

  });
```
seems to work when I try it with the `getVegaPromise` above as far as I can tell.

I don't have any objection to the `Vegawidget` object approach, just trying to understand whether it is necessary for the wait-till-render feature!

**Comment by ijlyttle** [comment]
I think I get the question now... The reason I proposed to create an object called `Vegawidget` was to provide an upper-level for a namespace, in case we would add more functions - we would be adding only one "thing" to the global namespace.

I agree, the functionality is the same - indeed I created `find` from the code in `getVegaPromise()`. Another possible approach, that might make things a little clearer that you are getting a promise and will have to treat it a little differently, could be to rename the `Vegawidget.find()` function to `Vegawidget.getPromise()`. 

I called it `find` so there would evoke the `HTMLWidgets.find()` name, as they both take a selector.

**Comment by AliciaSchep** [comment]
Yes! Makes sense re the upper level namespace.  Re the name what about naming it `findPromise`?

**Comment by ijlyttle** [comment]
Sold!

**Comment by ijlyttle** [comment]
## Updates to API proposal

I think I made a bad decision a little while ago, specifying that we return the `embed` promise rather than a promise directly to the `view` instance. The [`embed` promise](https://github.com/vega/vega-embed#embed) resolves to an object that has a `view` element. 

I'm sure I'm not saying anything new to anyone; moreso, I apologize to you all who had proposed accessing the view directly in the first place 🤦‍♀️

Its other element is a copy of the parsed spec - which I have not used yet, and have not heard of anyone else using either. As well, the vega-embed function for Observable lets you [work with the `view` object directly](https://github.com/vega/vega-embed#container), so this is not without precedent.

This seems like an opportunity to set that right before being committed to it at CRAN.

Accordingly, I propose two elements to the `Vegawiget` object:

`findPromise(selector)` - would return a promise that resolves to the vegawidget-factory object. I think this function would be (is!) useful for us to build the Shiny API, e.g.:

```js
Vegawidget.findPromise("#" + message.id).then(function(vwObj) {
  vwObj.callView(message.fn, message.params, message.run);
});
```

`findViewPromise(selector)` would return a promise that resolves to the `view` object, which may be useful for working natively in JavaScript, e.g.:

```js
Vegawidget.findViewPromise("#chart").then(function(view) {
  view.signal(name, value);
});
```

Internally to the `vwObj` API, I propose to change the internal element `vega_promise` to `view_promise`, and I propose to update the function-code, e.g. `callView`, accordingly.

Thoughts?

**Comment by AliciaSchep** [comment]
i like the proposed changes!  Although if there is `findViewPromise` I think `findPromise` should be `findWidgetPromise` for greater clarity

**Comment by ijlyttle** [comment]
I have deferred it for now, but I think I should write an article devoted solely to the JavaScript API: there seems to be three parts of it:

- the widget factory
- the `Vegawidget` object, containing the `find...Promise()` functions
- the Shiny handlers

**Comment by ijlyttle** [comment]
Leaving this open as a reminder to finish the documentation.

**Comment by sa-lee** [comment]
@ijlyttle have you thought about how ES6 changes JS API?

**Comment by ijlyttle** [comment]
@sa-lee I don't think it changes anything immediately because I don't think the switch resulted in any immediate changes to the vega-view API - but I could be wrong...

**Comment by ijlyttle** [comment]
closing in favor of #81
