### ISSUE TITLE
Proposal: R API for Shiny-access

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#54]
Hi again,

Assuming we are OK on the JavaScript API, it remains to finalize the R functions. I have been messing around a bit with some things, and I have some crazy ideas to try out.

The overall idea is that we want to be able to send signals and data *to* a Vega chart, and to be able to get signals, data, and responses from events *from* a Vega chart. Building on the ideas from @AliciaSchep's `vw_bind_ui()` function, I think that functions that send stuff to Vega should return *observer* functions. Conversely, I think that the listeners should return *reactive* functions. 

I have made a few sketches already, and I am feeling good about the observer-functions. I have some first ideas on the reactive functions, but it remains to be seen if they will work.

## Observers

I propose these observers:

```r
vw_observe_to_signal <- function(expr, output_id, signal_name, run = TRUE) {
  # stuff
}
```

```r
vw_observe_to_data <- function(expr, output_id, data_name = "data", use_cache = TRUE, 
                               run = TRUE) {
  # stuff
}
```

`expr`: a reactive expression, like `input$slider`, `value()`, or `data()`, that evaluates to the signal-value or a data frame.
`output_id`: `character`, the id of the Vega chart
`signal_name`, `data_name`: `character`, name of the signal or data
`use_cache`: `logical`, indicates to use the change in the data since the last time the observer was invoked.
`run`: `logical`, indicates to run the chart after invoking the changeset

A couple of notes here:

1. I want to denote that these functions act like `shiny::observe()`, hence the "observe" in the names. I thought that although `vw_observe_signal()` might be terser, it might also be a bit misleading because we are not observing the signal. We are observing the first argument, and we are sending the value to a signal, or to data. Other naming ideas?

2. To use the `use_cache` option, my idea is that you will need **dplyr** installed, as I am thinking to use a couple of calls to `dplyr::anti_join()` to determine the changeset. I have no idea if there will be a noticeable difference by using caching for smaller datasets, but I imagine it might make a difference for larger datasets with a remote shiny-server (@sa-lee might have influenced the investigation of this option). Setting `use_cache` to `FALSE` would invoke a changeset with `remove` called with `vega.truthy`. 

Let me see what I can do to implement this (I have a working version of `vw_observe_to_signal()` in my `shiny-interaction-delta` branch, but I'm afraid this branch might be a bit of a hot-mess the next few days. Once this works OK, I will propose my crazy ideas for `vw_reactive_signal()`, etc.

**Comment by AliciaSchep** [comment]
I like the idea of clarifying these two classes of functions and having a consistent API for each of the two classes. At the moment, don't love the proposed names though... IMO are a bit awkward / un-intuitive (although they're making more sense to me as I think about them more).  I think it is because to me 'observe' only captures half of the action, the other half being the linking/setting/binding/sending to the signal/data.  While 'to' attempts to capture that aspect, it is not the verb/emphasis in the name.  The initial 'vw_bind_ui' name was trying to emphasize that aspect, and was inspired by similarly named functions from ggvis (https://github.com/rstudio/ggvis/blob/master/R/shiny.R#L59).  Not at all attached to that specific name, just think that names that emphasize the linking of observed event to signal/data might be clearer in signalling the intent of the functions.

**Comment by ijlyttle** [comment]
I agree - `observe_to_signal` does not flow well. `bind` is more evocative; `observe` provides precision that this returns an observer. 

Perhaps precision could be saved for the documentation; we get only one chance at evocative.

As a next idea, how about `vw_bind_value()` and `vw_bind_data()`?

My concern with the "value" part of the name is that a signal is not necessarily a scalar value. Is "value" OK? Other ideas?

I'll change, provisionally, to these names, but happy to keep talking and iterating.

**Comment by ijlyttle** [comment]
Another crazy idea, looking at the R API for getting and setting signals and data:

Observers:
`vw_shiny_set_signal()`
`vw_shiny_set_data()`

Reactives:
`vw_shiny_get_signal()`
`vw_shiny_get_data()`
`vw_shiny_get_event()`

**Comment by AliciaSchep** [comment]
`set` seems clearer to me than `bind` actually, as it very clearly indicates the direction of the action, that you are setting the data/signal to be whatever the input is.  And the parallelism with 'get' is a nice bonus

**Comment by ijlyttle** [comment]
Let me see what I can do....

**Comment by ijlyttle** [comment]
I have some this working in my `shiny-interaction-delta` branch, and I still have a *lot* of cleaning up to do. I wanted to run the current proposal past you all to see if it's OK.

### Setters

```r
vw_shiny_set_signal <- function(outputId, name, value, run = TRUE)
vw_shiny_set_data <- function(outputId, name, value, use_cache = FALSE, run = TRUE)
```

These functions act as shiny observer. Internally they use `shiny::observeEvent` to act on the reactive expression represented by `value`.

### Getters

```r
vw_shiny_get_signal <- function(outputId, name, handler = "value")
vw_shiny_get_event <- function(outputId, event, handler = "datum")
```

These functions act as shiny reactives. Internally, they return `shiny::reactive()`.

For the version of vega-view we are working with, there is not (yet) a `addDataListener` method - but it does exist with the *current* version of vega-view, so there is a little more work to do when we will have moved (officially) to Vega-Lite 3.

### Arguments

`outputId`: the name of the shiny output for the Vega chart
`name`: the name of the signal or the dataset
`value`: a reactive expression to which the Vega signal or dataset will be bound, e.g. `input$slider` or `rct_data()`
`run`: indicates to rerun the view immediately
`use_cache`: if TRUE, will make a changeset using the changes in the data, rather than doing a hard reset.
`event`: the type of event, e.g. `"click"` 
`handler`: the name of a defined handler, or the body of a function.

### Usage

Here's the server function I adapted from an app that @AliciaSchep wrote to demonstrate signals: 

```r
# Define server logic
server <- function(input, output) {

  # reactives
  rct_cyl <- vw_shiny_get_signal("chart", name = "cyl", handler = "return value;")

  # observers
  vw_shiny_set_signal("chart", name = "cyl", value = input$slider)

  # outputs
  output$chart <- renderVegawidget({
    vegawidget(spec)
  })

  output$cl <- renderPrint({
    rct_cyl()
  })

}
```

In terms of internal implementation, the `vw_shiny_get_*()` family is the trickest. Following Alicia's lead, internally it sets a shiny `input` known only to itself. The reactive function returned by the function itself returns the value of that `input`.

As well, following Alicia's lead, I am trying to work out the best way to provide a collection of standard handlers. Currently, they are defined in a JavaScript object, but I think it might be easier to manage them on the R side (as Alicia had done).

Thoughts?

**Comment by ijlyttle** [comment]
### Update to getters

I have moved the handler repository into R and have made a couple of functions to access it:

```r
vw_handler <- function(body) # returns function(type)
vw_handler_list <- function(type = NULL) # returns list-like structure
```

There is an internal list that has two levels: at the top is `type` (`"signal"`, `"event"`, and soon `"data"`). Within each `type` there will be different function bodies (`body`). To print out all the available handlers, use `vw_handler_list()`. Here's its current output:

```
> vw_handler_list()
type: event 
args: event, item 
body:
  datum:
  ------
  // return null if nothing there
  if (item === null || item === undefined || item.datum === undefined) {
    return null;
  }
  
  return item.datum;
  ------

type: signal 
args: name, value 
body:
  value:
  ------
  return value;
  ------
```

I think this gives us the opportunity to compile useful handler-functions, as we go forward.

The `vw_handler()` function would be used in conjunction with the shiny-getter functions, e.g.:

```r
# defualt: handler = vw_handler("value")
vw_shiny_get_signal("chart", name = "cyl", handler = vw_handler("value"))
```

The `vw_handler()` function itself returns `function(type)`. Inside `vw_shiny_get_signal()`, because (in this case) `handler` is a function, it is evaluated with `type = "signal"`, which then returns a string for the function-body.

If `handler` handler is a string, we're done, e.g:

```r
vw_shiny_get_signal("chart", name = "cyl", handler = "return value;")
```

I think that the defaults, as @AliciaSchep first wrote, will cover most of the uses. As a second level, we can provide other handlers in our "library", and we provide a way to offer the body for a custom handler-function.

So far, this implementation is working for me...

**Comment by ijlyttle** [comment]
Just to update a few things from today's hacking:

Because the shiny-setters offer the option to delay running the view, via the `run` argument, it stands to reason to have a function that would run the view in response to a reactive:

```r
vw_shiny_run <- function(outputId, value, ...)  
```

In this case `value` might be hooked up to a `shiny::actionButton()`.

As well, I have added a `...` argument to all the setters; these get passed along to `shiny::observeEvent()` so that you can, for example, customize what happens at initialization.

I have started to try to put together an "official" set of shiny demo-apps at `inst/shiny-demo` - these are accessable using the function `vw_shiny_demo()`, which works a lot like `shiny::runExample()`. I have been adapting the apps built by @AliciaSchep and @sa-lee - these should appear there shortly.

**Comment by AliciaSchep** [comment]
Took an initial look & still formulating thoughts (changes seem great but want to wrap my head around the setters functions) but for now two comments and a question: 
(1) the shiny demo calls 'slice' function from dplyr but doesn't load dplyr (perhaps the dplyr dependency can be avoided though?)... got an error running prior to loading dplyr.  Demos look really nice though!
(2) in example signal listening app the reactive listener for the signal starts off with NULL rather than the initial value of the signal.  Not sure why yet... 
(Q) What are you thinking about in terms of event/signal listeners outside of shiny?  The earlier `vw_add_event_listener` functions were not shiny specific, as you can add an event listener outside of shiny do to some stuff via JS only.

**Comment by ijlyttle** [comment]
(1) Let me see what I can do to remove dplyr from the app - I *should* be able to work around `slice()`

(2) This is strange - I don't know if it is related or not, but I got different behavior on your shiny test than you did or what travis got (and then travis started working differently). On my mac, the shiny test would fail, but it passed on travis, until it didn't - and the difference was in the value of the signal-listener being NULL vs having a value. FWIW I am on a Mac using shiny 1.2.0. I'll try to use a few different machines (I have access to a PC and to an Ubuntu machine) to see what I can find out. It was bugging me, but now that you have said something, it's bugging me more. (By the way, it's a shame that the shinytest work that you made seemingly has to go away in ES6-land - I hope it can come back soon)

(Q) I was wrestling with this for a bit before I decided to restrict my field-of-view (for the time being) to Shiny. I'd like to keep the `vw_add_*_listener` functions but to propose that they could work a little differently. The `handler` argument could take the *body* of the handler function. 

Here's where things get a little weird for me, and I run the risk of trying to cover ground that you already know well (and I don't). The functions described in the `vw_handler_list()` don't actually *do* anything, they just return a value - as I understand it, a handler function has to provide a side-effect, changing something outside itself. For the Shiny case, I managed that process by wrapping the provided function in another function that sticks the value into a Shiny input. 

For the general case, we can't have any idea of what the side-effect is, as that is up to the user. As a first idea, could it be useful to ask the user for a function-body that returns a value (so they could use the library), then for a function-body that carries out the side-effect of doing something useful with that value? We would then be responsible for composing those functions in R and sending it to JS using `htmlwidgets::onRender()`. This is where I was spinning my wheels when I decided I needed to focus on the Shiny bit.

As usual, sorry for the novel...

**Comment by ijlyttle** [comment]
And now to add another chapter to the novel...

I found out that a "future" version of vega-embed should work with Vega-Lite 2.6.0, which I think decouples our CRAN pathway.

I had been holding out for VL3, but I don't know if that is even going to happen in January.

By updating vega-embed, we can take advantage of the `patch` option to help with signals, and I think we would also have access to the newer vega-view's `addDataListneter`. I think that this would be enough to justify a CRAN release (thanks to @haleyjeppson for the latest nudge on this), perhaps with the bonus of working with node.

We would then be free to work on a branch with VL3 release-candidates, which should smooth the way once VL3 is well and truly released.

I'll do my level best to get everything ready for the end of the CRAN holiday (2019-01-02) - if we can include the node-stuff, wonderful! If not, it will make it in the next release. I will have to double-check, but I don't think moving to node will require any (or any big) changes to the API - I don't think we would be breaking anything.

Ho ho ho!

**Comment by ijlyttle** [comment]
To wrap up this issue, and on topic, I think I am ready to merge into `master`. I have a couple of articles that will go into the pkgdown site that will explain things a bit better.

Just to emphasize that I am merging into master so that it will be easier for us to look at the documentation and to discuss - if there is anything that you think should be changed, I'd be happy to look at it in advance of a CRAN submission.

## Shiny R functions

There are four functions:

Getters that act as Shiny reactive-expressions:

```r
vw_shiny_get_event()
vw_shiny_get_signal()
```

Setters that act as Shiny observers:

```r
vw_shiny_set_signal()
vw_shiny_set_data()
```

We will have a fifth function, `vw_shiny_get_data()`, when we move to VL3, as the `addDataListener()` function is in a later version of vega-view.

## Javascript R functions

We have a couple of functions that we can use to append a listener to a vegawidget (a third will join them, soon):

```r
vw_add_event_listener()
vw_add_signal_listener()
```

## Handler library

This is the rabbit-hole I managed to find my way into over the holidays. Both the shiny getter-functions and the JS listener-functions have to supply JS handler-functions to Vega.

I noticed that we could separate those functions into the parts that return values, e.g. `item.datum`, and parts that produce side-effects, e.g. `console.log()`, set a Shiny input, etc., and I tried to put something together to allow you to compose these.

I also tried to build on @AliciaSchep's idea of having a library of these functions, or function-snippets.

Accordingly, I have introduced these functions:

```r
vw_handler_event()
vw_handler_signal()
vw_handler_add_effect()
```

and a couple of functions that work in the background:

```r
vw_handler_compose()
vw_handler_body_compose()
```

If you wanted to build an event-handler that wrote `item.datum` to the console, you could write:

```r
vw_handler_event("dautm") %>%
  vw_handler_add_effect("console")
```

The arguments `"datum"` and `"console"` are defined in the library.

**Comment by ijlyttle** [comment]
merged
