### ISSUE TITLE
Question : how to render a json spec generated elsewhere.

### ISSUE THREAD

**Issue by djouallah** [vegawidget/vegawidget#64]
Hello

sorry, but I can't see it in the documentation, I have already a json Spec generated by Altair, is it possible to render that spec using vegawidget and use it in flexdashboard ?

**Comment by ijlyttle** [comment]
Would the `as_vegaspec()` function work in this case? It can take in JSON, or the name of a file that contains the JSON spec:

https://vegawidget.github.io/vegawidget/reference/as_vegaspec.html

**Comment by djouallah** [comment]
boom, work like magic, great works thanks
