### ISSUE TITLE
node vs V8

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#84]
This is a continuation of #44.

So I started this trip down a rabbit hole that started with the question, "now that V8 is ES6-friendly, should we try to move away from node?"

Let me start by saying that I think we should stay with node (but can be convinced otherwise) - I'll explain my reasoning then link to the rabbit hole I ended up following (and I had been there before).

For me it comes down to a few things:

1. We have the node capability already (thanks @AliciaSchep!)
2. Node is more capable than V8 ([link](https://cran.r-project.org/web/packages/V8/vignettes/npm.html#what-is-v8-not))
3. We need one of those capabilities.

To expand, and here's where the rabbit-hole starts, I think we should support `vw_to_svg()` for specs that use datasets loaded using a URL. With node, we have access to the network; with V8, we don't.

The rabbit hole is how to handle a proxy, for which I will create another issue.

It seems to me that we need node for things that have side effects, like network access. 

For things where we just need a result from a "pure" function, would we want to use V8? Or would we want to use the method we are using in node for `vw_to_vega()`, where are writing the spec to a file for node to read, compile, then reading node's `stdout`?

**Comment by AliciaSchep** [comment]
@ijlyttle this has been on back of my mind since the update to V8 package! thanks for reasoning through this...

Re the V8 question when node isn't needed, are you thinking of many more cases outside of the `to_vega` where that might be the case?

**Comment by ijlyttle** [comment]
I had promised a link to the rabbit-hole, [here it is](https://github.com/vegawidget/vegawidget/issues/85) 🤓

If we are thinking about using V8 for "pure" functions, the immediate case that comes to mind is spec-validation, which I think would be pure, along the lines of `to_vega`. Another case that comes to mind is the `ggvega()` function that we look forward to building in the `ggvega` package - so not vegawidget directly, but still pure.

**Comment by AliciaSchep** [comment]
Would the JS parts of spec-validation likely be through another package though (e.g. `jsonvalidate`, after updated to `ajv`?) (which uses V8, but wouldn't require this package to directly call V8?)  

I guess my lean is that converting `vw_to_vega` to V8 doesn't seem like something that should be high priority (although have no objection to that change!) but that for new functionality that doesn't require node (e.g. the spec validation and `ggvega`) that using V8 from get-go likely makes sense...

**Comment by ijlyttle** [comment]
You're quite right - this sounds reasonable. 

I'm with you - no need to do anything in the near future.  

Thanks, for the discussion - I think we can close the issue 😃
