### ISSUE TITLE
knit.print.vegaspec() does not work on Mac with knitr 1.23 

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#92]
There was a change in knitr 1.23 on the `svg` device is implemented: yihui/knitr#1705, causing me problems on my Mac. It turns out that I had to install [XQuartz](https://www.xquartz.org/), which, I think, went a ways towards solving the problem, but then there was another problem. 

I found a workaround, to define another device, `"svg-vegawidget"`, which avoids `grDevices::svg()` entirely; this is outlined in #93.

To implement in an `.Rmd` file (like in our README):

```
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  dev = "svg-vegawidget"
)
```

I don't know if this approach is "correct" or not, but it "works for me". 

May I impose on you for your thoughts, @AliciaSchep?

**Comment by AliciaSchep** [comment]
Are you also having issues with other svg on your mac? E.g. ones not made using 'vegawidget'? Or is this issue specific to how vegawidget makes svg or how vegawidget is handling the snapshot workaround?

**Comment by ijlyttle** [comment]
I have to confess that I had never succedeed to knit to svg working on my Mac, other than this. I would go through all these installation steps and I would still have a problem.

I think that our method (well, your method) does and end-around the usual svg graphics device. 

I also think that the change in knitr tries to initalize the svg device, but if you are rendering a vegawidget, that device never get used, in favor of our "device".

By specifying `"svg-vegawidget"`, I am avoiding to initialize a device that I can't get to work, and does not actually get used to create the svg.

Perhaps the value in `"svg-vegawidget"` is it would avoid the tedious (and as yet, for me, unsuccessful) installation steps on the Mac. 

Maybe I should try to get the normal svg device working, and see how much installation that would involve.

**Comment by ijlyttle** [comment]
Update: Now things are working OK on my Mac using the default svg.

Methinks I need to test and poke-around some more, but for now I think `"svg-vegawidget"` is on hold...

**Comment by ijlyttle** [comment]
I think the issue, now, is for me to document that Mac users should XQuartz...

**Comment by ijlyttle** [comment]
Closing in favor of #88
